apiVersion: v2
name: open-webui
description: Open WebUI - A user-friendly web interface for LLMs
type: application
version: 1.0.0
# renovate: image=ghcr.io/open-webui/open-webui
appVersion: "v0.8.12"
dependencies:
  - name: open-webui
    version: 14.2.0
    repository: https://helm.openwebui.com/
