apiVersion: v2
name: tautulli
version: 2.16.1
# renovate: image=lscr.io/linuxserver/tautulli
appVersion: "2.16.1"
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
