apiVersion: v2
name: tautulli
version: 2.16.1
# renovate: image=lscr.io/linuxserver/tautulli
appVersion: "2.16.1"
dependencies:
  - name: common
    repository: https://fireball1725.github.io/firelabs-helm-common/
    version: 5.0.3
