---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bambuddy-database-url
  namespace: app-bambuddy
spec:
  encryptedData:
    DATABASE_URL: AgByMcsW5VO/GvuVUqRUJIQainX7jr3/g0saPXxBrM2PMftuuf4WO4k113Y2TQdebA1qFbvqi/qC04nts2nUNLhPsxJHWRdkOIQOEIjj0XE2gjXGB1fuX5L3BFcstSg5y52kBBMBHyBhD6lSzXqFjyT/vFA06EpGULHhHC5o0m69uh5Q2Zl9TSP6dc3bgv0k7qu7/h08QqtkiQdkaLyVf0037bbN0mxPPb1afqsmcqsXUDOro9eJR+AiJZB8BWa9/W/ym8PqtKcRBp3kFbX9QnXlqOw0r7TaetF/JLFsMYx6YZAj/P0WpVs9k3sgpn0t9Fwnj8DP2TY98m7rFqpDkoCBeuBGcOPaZ1/gI+hnzWsuMkEsZms9JlUlWfPMa7HXCemwsFxuB+zSPM7exQmFv6wsBV/ujnrX3jrun6MaW0PGZYRW9a06JYKfhwnvjDAOgUbGTjHOrX21RVK5XH+2hINFA1KEawy4Z5OJi3wvHDGcI9n7sjVfkbsVMMWrfGUacp8cilhXX5QSH5AS4ecMyYu7VNsxQLe/j1osTFht/X5z+yKQwhk29kJ4khrw3XMuxYnZA2rHmy+dSXndWBVPx55YnZqPLCP9rlK0vSHateOJm1wyETOW7+Q4/HkH3NuUtZnY6JXPRBjiIvYlcYy5AHR6Q66PEJNFNZhFdH4asoXGPAwXeeDuE/q2R1vTc/Cl2QU7jYdw50LsqxKiuw/pYgeuTDBYEJuRQzTB3KnHkuEcuqR8Irhus+mrxQxJtnoQkkXlYDbRM+E9pfrsU+4en4yX7DL8o2AnL8rzOxQryHZYFz7fn64/gmfLr1L8
  template:
    metadata:
      name: bambuddy-database-url
      namespace: app-bambuddy
