---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-mcp-secrets
  namespace: app-ai
spec:
  encryptedData:
    HOMEASSISTANT_TOKEN: AgBWivuAWyvZULYidOoaCuXGK94yZ+Wc5c4o21ihdkGrwvkN66eGDWNQjv3hMw+cx7ILxOqjPgfXRg3Gxwltoz5vIvYc1n+HObUB2nZrCeBHm1d0CCAs4zGCjDgNbPN22Qs738uDVSamM8gHryXCS+d3R16E+m5SdLOLlaYJVm/qhkTAFTa4K1Klq5sRkGsDxN8kSWHXt2IxPxNTMura/OaHXd6S0xStoiRW3TO2MmnHHnlV4vTHLmdpghsDf/BeUEZowIllXrpET4aadHOxfbio1tG8YTpGJBEL7WfZwSdNEuHZKSaly+ngGufSqq7VagqJL5e3bzsN5tpfUUESzGl7OiLfVdE3v/kYCL31QmCsSUuTgxlK5l92lc1e3Yh4hPL965v525gSrpy0LcsUMs8K7zHo6IdXWR5D7arpLsuLdobidc3zLhnwQ1cae5E5k/en4wKIY9IbNwx8lO/zszkRYeugygjbRuKA76eKwjE1L+hDU1shNpISYbMmZrcr38TWff7ET1OROFePL7BLBFwqosxh0puxO2F3Xv+W2D0bk2Un9gBUYDlevaoZqF16qosK3ZPrvLHM+mA8Z8idW0RItO6LdNO9HSzKb6vLNpyr304Cw4yqCkiQQ3kE8/+liYSRWkOxUPZtTxyYCuEYTGlNqL5rAb5Ih2UkKhYcWQ0HPJrziW7KVg6ha+osQ62mYq8hRBkv1zTamBv3j0VqDg0+bZJi/x2oPC3yyxUFcKtfCtgkjfMBzCXk+t4iRq6/cZ8EYCIEswojyvCGFBoNYzksqgNHZrLqEAC4CgvI2s0v2nDFjvw0pGE+dW7VdE6vMKLhSbHuC/4zL2+aiy+9lIKWhGhFgANkPJkMCh3K6730VLrQ/f+zfGguOLgsOr/TE1vUJ73tr6mS/9L2iz8KoAw3Q7aIdeq4cTzqIzF0N+98+hGEcVZdMcc=
  template:
    metadata:
      name: ha-mcp-secrets
      namespace: app-ai
