---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-mcp-secrets
  namespace: app-ai
spec:
  encryptedData:
    HOMEASSISTANT_TOKEN: AgBrcHHDFwb3MQoQII6kir9OElMz6Rzz175NAoCY48oRwx+URSlAQOO0TDmavJ5CToWRrpYSoWSbsJ//Lp7e/lRwWzq0rcJ6FaIhe2j7kofqZ5fMCGjW2k0GURaiK3ixGr5cmGhL60nAdi5/ro5Lzib/8b1laQjdTLa3lDvHxILPHueVTaAc2PLzVok6opRJxXFMQvwVYcqM21Og1txCtRkl4dZjS1gLFUNoxhHpt1izu8TlohEONqeMJkHi1hZgUHEgNifL9L2vZSoOIVbL3PIF0eKsrflMpIALlr7mx58+kM/vV1+08T5O6aB0S8KeTUtPn36zoa2W6GgdyMUAPm4XSLszfNk7PYleq1EJ1tXEtMaWEe3RWZv4dxXUPk6VbgFQO45MkZe/XlAyjokfl5ZeH3E54+qXWuaz7z1nTZ9XJ+Efyz/6jCA9CojrocqbaOMn2aRgjGuHEPHK3vLbOqGQX2HbEv+DLrxx52ce4mv+yH/R6jLYwK1AHejti1ppujvyXEBzW79gVubhej5hQ5p8KTnpwY/NtdmHb+TEo0fd0pB/kVm/HynPtwdiYvbDCkg/nl3aOGWOPm0CvwT1crVIi+JvT/194PWlStdLZRqySbcmzi2a8ocXPGg/4k9/qwzVbYqjerTempAvdRKGTvays+8O+WUexhHrQV7kDwrICSXZYtmzHDQ3PRi3wm6D3xfmSqjT4SH5LeOqctX2n8aZKv2KCZxZ2szgz5aaLqvUBLqIMw4sBITneA5YeEUW/rqX/NrQq5kxNZh2gQ+h2MhnFX6LdN+oxJNLCle0myyG6iJ+A5+ol5sJor2PLipm84o68k8Q6d9G3CVcotOPAIU8vu3S1C1zpw7dS/7tBt4h3OrGzQeckMHLk8njAPP7PC7mNatFMwh0esQsMtPEoXKn0+um2cNzPxVzIrrCk2gN3R1gOqY82O4=
  template:
    metadata:
      name: ha-mcp-secrets
      namespace: app-ai
