apiVersion: v2
name: sportarr
version: 4.1.4
# renovate: image=docker.io/sportarr/sportarr
appVersion: "4.1.7.1117"
dependencies:
  - name: common
    repository: https://fireball1725.github.io/firelabs-helm-common/
    version: 5.0.3
