{{- if .Values.mcpServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wikijs.fullname" . }}-mcp
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "wikijs.name" . }}-mcp
    {{- include "wikijs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mcpServer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "wikijs.name" . }}-mcp
{{- end }}
