---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wikijs-mcp-api-token
  namespace: app-wikijs
spec:
  encryptedData:
    WIKI_API_TOKEN: AgAnb2UTzhUQzoYS65s+4TvZvAaYs5WGBwaNtpthhNYa4KqEXwrXgE0Y49g2vVQHv2qmIY8T43fxqbnWcrR6YxH3CYxomBqoxwyd4IM2+j72iEGhSgl1UgzEdPOAyqSnz82wIfymUeJkfNJgVRCIey71iTKAga+0pzLgEJ8IOG/ZmtkRp8hFJdEv+0BPPlH2eWGkrQknyVHyn5N+D+sUKJoqFmcx5RdJfiE8ZQmGojdNZ36g7DwyHQ6f9g3H/lAwVY9AMcCH69s1WXHZTAkh22yOl4aBFzTDuDV3/MhDt3jhP1N8oESZ1lKal79psnYOlptFWawoMVTWWuoZOjDjEZXq10oHI7b3qIjKAvLk+1Z/ogc9R+U0LAJ6mxoRJpeExKVS6MhAgp4pvcdBR/yqy+W+upupau1UHQWCtHVmnziVvMFGMgCH+rSsjM/eu9tYPMjA0F0Wh5WS7I3y7qu6limxyUWiba4VNjT7v7g7o4jFwehUcq+Zr7ISbA3JP5MoDG4oT5zSa9xYz691yCQ4yN6LRePlzxZ+IwEqhHnH39VKlU9Ity5369sbZPIePytUikTof/RTzodX2eyTUkG4OotbaRvo7lKQiNN/3HGaJdvf8Z/McvKgx7GpjP/ZOnUbWslOVzViSurKLMHfrgAH3q6Ts8Re/i/HxFN5qqG/wCSAXwIJDFyQ8euKH3NobJvd7JXRvjw4QL13h9eQpL01Q9RB1krRRJILdfHDTySOc2PtKSa8aWgfn88fheS4MlYxl7dNLjbWnCjCmoQq3C4lejjBRAWhW0/oSrQgwjU4vetEGNHQVo1N48pSuADWH0s+wbKqYOo6qdCpXxd3Mn1514+AxiJBF75TU2pJk3tJcc02KhvK9EdBa9N+asEwu4jVhvSrebsmDZgnDtv3aVHQi2xizoxHG+tD3zEXB2WyyzBZri0krDGv2+1HhSxxmRCAocMTku6WtUpVRIz8w3lT2VKTor9LBG14AyNbMACDsgsrU18aP4LYtgJAlqmsn2oOD8Z0/IpWZ0e6KD9vp6YErOvx2PjbN5OeF60PS49guuyUOPOKxfDwU94tH+a2GzGusxZUyh1r8TxKyWQigwuCpboYsUtkb53BaOi2Ni2NfdIpmXiXChnXvfnq9muLA0tl19jlEnHlHeXrZShGFnZjtrR7kt8SlBD7ApRm/cWUMCs6xYA3iEoCiYqE62SpfVPbZrRrQWR7Sgef8SA53Q7hQgzz4jczppUTmVFO8FQQWk3Xpb9l+5HLUfYBh0XxYcDuDdxkgrzLqoRYFhLx96fjbVmCkfs6wGCWXJmns8Js7sZYquNNP3dXCyfSgecrwoKl55ZfJOVc8OMV2+fF8RduNRJ8hOIO/zPxyQ==
  template:
    metadata:
      name: wikijs-mcp-api-token
      namespace: app-wikijs
