apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "error-pages.fullname" . }}
  labels:
    {{- include "error-pages.labels" . | nindent 4 }}
spec:
  errors:
    status:
      - {{ .Values.middleware.errorStatusCodes | quote }}
    query: /{status}.html
    service:
      name: {{ include "error-pages.fullname" . }}
      port: {{ .Values.service.port }}
