---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firebin-kicad-access-token
  namespace: app-firebin
spec:
  encryptedData:
    FIREBIN_ACCESS_TOKEN: AgAHw7dSUp1HrFQG5znCRhwZwxNTbx9y2M/hD2f6qMSaQgJ0pqGRU9IuC/nOrpAQsXpXztWoBFyxDdRbrLpXmg070BqiXNZKfhau53i1bNRksvJidG57vXBtxtHt27xBMWp4ruLGFne3EBqcZ2jDs7mpEh1AODEri4g73bG1L2ZxmyEkYkGrgI0fcAqb04n61+G8ScpXTZutJStgpZdkRsbhrtlawdpr4+E23Y0TOu3i8I0G4p/ly6A+oWKsPeWjsDBkTsw5FWm1mw9WnuHAyP7ga0rpufKMSafRbCUYDQBX6wltCoAZ9AMo3YHSqQ7zjKPEWPQhMlCl7FvHvisc/cnP/NyGWDlnsQdJLDasfbBGEzKLDE2XyUKESS1Q8FC/qW6u1Zwfg2fClVA9+ko6LDNrkPgz3gTiXfKjuLCTZiR7q00CDV914nfg9V2kEclJkB0xMBXYl3sFSdLxSkgm3ULuYFOq2QXCy8V5U6bztxat8meDvEyb3CuvTS2iRAKS2MgnN1aKowNBEHJYxmuT8leDw/7hFpofhlKVrf+rc85Bl7t6lfgtukfnsxFHQ5jf+BPitC6y8QkeXi40PSSfY1oY0i8jvJF8X7rW7OdJOnl6a9IOtfn4a8xDEqQxHNonDRtZCXfithqtgiaMgts0k80055SkUpi/KpkLGFRMKXovGf5nr+fMykIEQiW9kc300HG61Nsv4xcQhda4ETgt3xFTMY3AsJvAMV3ie3IQZhJGZ0/pWdm3iJFAO+PvaVDzx5UQCzsn
  template:
    metadata:
      name: firebin-kicad-access-token
      namespace: app-firebin
