---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: app-leakyfaucet
spec:
  encryptedData:
    .dockerconfigjson: AgCQJ74/vzMR85JGB7wqdMKU1FSFr6RLMBBBq7nj4gfqjrg6eo5MinojX6Sd/NGVN1vYuuKVmBt3XNsjkY3zuLklqMNyct+sUgTYyh28wntFJczXeQQfNDaGaHtmeJZxopxxXnb203V7zzv2r03hAjJ36tb2N1RIDxweO7709H0GZSrJEFbD1iiAx7gp7BQyBedNyop+fANzRFEBeA7IYzjMv4OCVT68PUvMz7X/uDzZ4lkod+MJG5q3trRWkF1exuIvXVZRj+JonDvSZZiw00mnN6r1flqL8qVDtJY6QNAPmEJopAkO/e21NJoowDmaoytOAEC10Aq2qmZ+1GgwUfgal9SaEo9d8gpvIYcpT+weGEoX5GxkGbG18T/7MqQKqzwo4MrSnrZtB0XeNWOyOhSSRj7EQIqpY9l4a06JXK6FpfXbLjYwNnJRABajwWsHX63ULLY/qVwuiVQH+hXkeohCiMGySGFUiChMBmewsc4oInrbmWMaO+60kvCtkALWEYMpWd/cIobp1JBZTDKswWEkeg+dcEV3b/KrS1CBY8c8MYWw07/jnf4LtjVxEvPwwRpSG+nja/ToMnPWNC1gUj/KTOEc4k9oksxUgryUu2yA3UiIwcW5IH9oESyCZZGk/3+osPMh5Ni4S4sw2bA1NhuCzUpBKogd2sAaRw9zd0x1JSJ9y0zjwXXY8TRakVu4yJ6w0ZPYNJFTYTcLEXdJmmponjzUqOOaj6XbLjF1JP0pc+xjjGdj5VgLKTOrUaKzX1KrDQ/E5xx+PJ6apShsYN8iVMy0FmuWIoaFbiJXmBr1YHv5dIiWvZw7SajE9iA8tWGqPHVTnrOCfUi4K+bsviGFlLl5fzXxSrajnYJ8xFAHLRhUMFjVZ8WoRvaD3VsAXqhQExb1ByjCAL15qod6J6TikQzLfHudv4D2FdyyzKyWzc/Y8+N9HFhZ5A==
  template:
    metadata:
      name: ghcr-pull
      namespace: app-leakyfaucet
    type: kubernetes.io/dockerconfigjson
