---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: leakyfaucet-jwt
  namespace: app-leakyfaucet
spec:
  encryptedData:
    JWT_SECRET: AgAKl3r6uay6peDvd4u5Xv80k2vFE6hkoInc0QzzVPwsZnPa1KgHlm0qkeHArIXLpziZn3YM5euzqAQLTaYU9dmUkvRFdfpu8TnD2rrFMsrQMwnUGtk5/h1OlxtHgYe7oGCT2Z2G6hOpJdSPkyuBFp9ZyVTm6DJqE4O1EKUXKMlG5vjK5Y118Q96p7d0VSTclFeCtjSpbKxifdSOFlaJiJ0asyVV9bkvmYYWhPdBBcKWw90nKRa7p5QnjjzEFHXr5/8Tp3bWXy/Wi7OCr6KFuiiSuo2hg8xGc0VxxAhV1uNY69q0L3A5Lh3VH8/na+tzQarMwqAzC1rcZJx3PkjekDH9BMBHDPO0jtrkiHwJLMPQ2QcKrtWFahuhpukkhFu3wannzAhznHVGn7VhxQdI9GReXNRvurk0zXJ1lJzIuNXzGItEXXiARTW6o4fZ0mK+PydGE0r7ljV0IP6cksNkszOQVl4P4cXzKdLcPujAGlMvyCRU8gr2/Jh006RZtsmwLzNwcUKOoLXQDUW7Fqqkgeu5Y0sbPNf7JilZDCxiZmttmfbeQs3innmW7syQSIKpZalPNLv3JiSeLwgIvoCin8r0I0P9PmEcH4xJDQOMhDUInQHOKcZ3RmaoRHl4x2VvWyi5gwwUcIy8zof2hFfZ+/tIg+PaE6tiAZcjX6O9aOCMTa+d9tukllQQsJwEuGTSr6ydgS2v2C5Ywj6MDMLPNo7H1qRfwpNpm9/UprbClTlC+iMIkEPOnBFpkgtrBiNSsBR+3G/l7vyyNH4WrFUyhAmp
  template:
    metadata:
      name: leakyfaucet-jwt
      namespace: app-leakyfaucet
