apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ollama
  namespace: {{ .Release.Namespace }}
  labels:
    kubernetes.io/service-name: ollama
addressType: IPv4
endpoints:
  - addresses:
      - {{ .Values.ollama.ip | quote }}
ports:
  - name: http
    port: {{ .Values.ollama.port }}
    protocol: TCP
