apiVersion: v1
kind: Endpoints
metadata:
  name: ollama
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.ollama.ip | quote }}
    ports:
      - name: http
        port: {{ .Values.ollama.port }}
        protocol: TCP
