---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ollama-admin-nextauth
  namespace: app-ai
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgA8XDB7qPf6wYbZrVmQCjF8/zHPuEFZLSNCwv46eVs3DeauaDdhh5DVfRIsIqANOk0vBzgq/60U2TI22GJq4veq8vtytvuFG96P94gPtm+RvTVhjr2Wcc2sdx+BCzfUzAt0QCynsweGIwFMrnoSMWvdIfPON4ymRwm8efG0HdXzTI9bc2T87dlcpdc3RMB6C2rKJ4oF67Cm/lHJjZyq/tn40ZrHHcf3YKU8EaHXZGx2gP525LbfiUzVY9OCmlIRwhD1SBueSdAYyVHoo3kWHs+p9CFzlzYdUmYVgJw98GiYTlUt820J5VSGMscvny8RmH4mKB4qnceO9NfapjE7iXQ8gNH0xmcU4QdEAjh+IwQcv9DT0qa6Wo2LK7W6+B0EbMrYFH+t09pZ1e1txH/1VhQCqorNgZKOyu8keg4OBabqCusFD7sL1kE3TzWgsA1StD/GyZxA/DBvhVIEQ2Tgk1O0nNf7QLZR/L/bQRMcNB25B7XofflGcoIz0XkyAbPf0HKYooDjaYhNJkD/x4Vcp8uQI9GRJANEXcD2tfhDZzqRwoLxBjy3a4cNNIE2tSZ4/f0ep/bqP0GkxLXOmDi5W77d9dpavdHt11Yt1MwWpqNRmc9dANYAv+BLMMdn84R5+GqslD+PHMQaCNvUYmDFzRB/Sl7ePEQPrjIWHDK2EXtLbX6Ju567FYTr/v+jU86eaBSvfPzjW4tbYrAR5SIrT6YBFPf+lgT/WrJmHIfxiBxmehupr8DWcq+RyyD7pw==
  template:
    metadata:
      name: ollama-admin-nextauth
      namespace: app-ai
