apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unpoller-credentials
  namespace: app-unpoller
spec:
  encryptedData:
    username: AgCQyg9gKvAip5fM3jDhK37CuOLH328sQ/zcbRcXTtkqEpB8wRMk7ZjBh2xDwlEyEE1TCeXijom5mg5X3wd8UIGLTG9ICATxhihbImdnDZteymCJy4po5ygnMcOpUhvJJxohPpjPGZum9kkyhBzLWh0f1b9uA4csBDUQ++ylQ90KU4aaPwXt2ZN3hClEiO+i/VChnnoauv6kxC1zFq4SMjQ5hJtq6D8aE3tIbP5gyRd2R675bEKeub9WGZMEkpM35Fin+tDU8KSMBM0GyMA2d+w78sJVznv2nhstS3rR9z+Gy3JFs7sx50Na+2q6Fc2abgqWnw8Y09tsr/RAJxyqywOo28sSayW+7kDkbuHARmvgjkGIM1W9ksonWtMA+c7qyMv0P71G2RHOtltRLhM/WcudL0qfK/+/uid1vn1sYdWGNVlLuHqiQLUs1xRgdDmMYdUXRhJTbi0vhy23lqKJlIc8qeeeFqmLH9N4twNqOooE3FeBVTVcxHp4oJqdQdLDZRSDEeGorEMTe332aO0868GVuTbvM1Tl/2xlz5pkr8OzeqHwkXl66C30c+dsRu4ZcxjCB6erk7vTZTSPf5PxjPpgooqdqKYP98afInh8U3Il3qabpP9dT4Nxq8cMG5JNihKjKicJNrpecbT+eJoy5IFc+lXJpURRfIrB3pIKPEtTML8AFzEAkSsg4hMHRMU8HQxcA2g=
    password: AgBHt/CHGuJbFAJaA0vIIGTvDBJgVtqVRd6A3LvdisTuMylCuDqDb7ATM2MnHcazpc21B15LMemqug1zGxi+75hBJZaAUoQm+eZClnCVSiTxMf5rPdwM4wbKf06VuzsBdj14IS+rdGpLBlBjlRNmX14dWRAoPxL2zd2GV4TodJFMqpTy9TNcXwpg+2POcvglFclAVbyRwz49VWgsMKZ4zyOdI9W53f8LEC4ug5+lGAp9Kk2mfQe7rrDiJ7pWdBmg1Q5DJdusQopRQcvIi7LPrEODbxtEaVWQUiCxnzMajtKIAiUjZjfXV401Dunm7ks8lQ+b1ul4XRDPCOv5PtLx4pjPw+CXZbyie98QJt1oMVQfD9QybAe2uRS4KSELvxyw9+OPHCQv9ds+99moQHFuI15RmijmQAMuDfNhBXIRkGm8qtlJUIWwlLyTQZ8l/hgTiOI6e4MwenCrAvC+FW1mbuDNQS+n4RvPPVfknAp0Bqmx1UtCc7PRmDNugW3uXiKqI1HxeIKk/1G7gfet0rfGjdWcOEfzZX1Do2RfMcvdFWBz1J5LFcGJub1+whuceAgihNktUL9iIiI1OhGnKrlOFHR07iL5bzIzwySWMPyJoFz3GrSXkW/FDJkMVU1ZwDUhQeQbfKTw5Py84fwyomIYb/1YiFN/oAFYA5c=
  template:
    metadata:
      name: unpoller-credentials
      namespace: app-unpoller
    type: Opaque
