---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cribl-edge-leader
  namespace: app-cribl-edge
spec:
  encryptedData:
    leader: AgAPzKFMvEh6GGXv4G8S6WshjfAM7kEwO0g4m14OXg5Ce3l0B7s37BQg2cQ0un7aP4awM2ZytHzfr4K+t+v5X86HOyofy6Mq3sCie5aEcL0K9NxawbusC9HOyXDfzqnuTfaUnptN4pYsTbafPMsz+rlm7GD4QizyQPfUGqPEkdq24JM5z/UIcfASbJLAwrnhfvVp1EA9H8rfum1fxSM10qXqfZH9z9RH+8Ybzh13krkC08H0kA99APcuB9mEnSIjdgUr+hsKhFknaBdVOWb4zNtV7Zzm+U7Xi8qn+vTxeOeJ75CSltAqUoJI3fMI+ZzhpvISi3XWXj+/QJ7SM49iejWdtx1AA27c9CTKGkwLO3Jm55M/SOA9+AKr+ElcReX+e0N1AA2K9qgv2PTfa8z0kOWqdNxz9uia0SQhcr79j5DGZRKnLnbRpk1A94ThhXoqtc+4sfpW4v4cB7fplrjJNPYVNiGKWWMzlf9nlQDXSopt10+Iwu5LWzor1P9XSd9R6HC2lVLzpTLwYM3cAwg4BSZpNrnO6DxVwujwdXj7PNuoXc3qREb7OGZlkb1XFG90dpiKiBzITCOqneOe6oQdEpJ1kBsF1c2TS4v4iSIJ+bNnzM7C45mkEk9l+s5RX/Y/EfDJ1KVR7E0iQW6rGJqcoRqAsSxsO0mYPQyTjSRED2hxv6ZHW4/R3CXIYqfua7tC6gzPFHRKwK/ydCbtS+qrtLCQBPAby1W+MtvTIkMBHyrF2048THqePJHNZnYZT2PBO0RPayeo2JL8wj6hFTmQ3gICqdJuGJPImXgzvb4RTGBJlM9+9nkXhEU8fR7IwYEkshSUzhAL
  template:
    metadata:
      name: cribl-edge-leader
      namespace: app-cribl-edge
