---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBN7ucUh5qGaw9gzt8rgfgcCriD82IXore2gOBooSU5iEFYuWqH0p4KosjLPqOqBDaJB9GXOurbaOit9C3tRvhoJCmCG6QQ+RtcBZ2mqw6Wz11Yz8rXGd/xwrfdyl1+PMN42SaRNz5FHxbkrlf2esSbEmQEy3L226qkFPiYBp/oUFy8M6qYDmEIkDwJfE1seMKKEQyLKW93bpTT/BhEQnyv8MNGtaESYuJjCyeh0JD3Ew11Id4Iy5raDvf15ReebfSUrmurRcR2v7wlMrVjdwfZw0s8biCIcvr11y5WCR7Wad4yQWsbEk6NEou06bUWSx/ftQ8+AijkK8paQ6tNckmEUvJM1EEqav2ozh9GBj7TbRRx2VfsNr0dDd8RfuabfcPw3YqsRxJ68B6+KECMVjpfDz+9y4N3MezBt7DDk2v4kyxvfMlVLN7Vi30r+kT246ba13ijyZEEVrnJQPFWFv5gkN1DQMKzZLtQunbnEEQxn5n8WF3/jFfdR6fNyk38k4Dp0geTI2bZw4ax0Dj9fn5qhdVk3YfsliXm+sRyiPu/czRi+cappywGs3m9SeZBINIEkfQtgLLJuVtJUtLspcP0fzmzc3gjGexnDY2YGllVHSA0lhw9k8Vi1hfHixIyF0LMoWPN09Cgl1Q9pzo7aI9EndPJxyFHy8s021ZNE66GObgCl0VgwFKVQMo88pIp9bIgUB1xHOoDuWq7UXYK4jb+BbIoNN2jphj5TEzWAs595WDXQ8K4+AMP
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
