---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAe1IMg0d7xRcKrV6V4tT8NelcRYaemY9W5xH04QWWX8XSOcplR7Ah2X7ZhaKN4vm3llc0x/aRzueAFYj+lC7W2SNHUOPk2ojre4Kg0JQQSXkjUy6Peig8xdVxG+Q6syBnBaRIdZAbY9AjCBCw/YVbpXgat5ZZK1gGyA+40fwigfrhn6N5h0j/V0OXpz2jgpcx/wC+dl/Agmc94DvZ3884D8C0rbA5lky2q6LoH+OR88YecRBdjIei+CYEHeToAUKMjIxmbPnKeegbOgoRPzOWMOeqpqsOUQq/D5QrgYjdCoH31lYXsSBgex3L5y6eDl79VpogKDSQijQBrJAHXurh64I+Ivm/oyM3gZBResHb1eab0iZTxfg0rIEPIWdSeag6tQAASEYoBAls9wEwVjTTypE1rf4bhzzIlru9tKrETb02kFFXct/v3zlQQ1edrvfz4KbLKx2UzpE+6CuPEKmkhwZ4LYpuAcQf5BJlHzvryDyGZVH7ozSilaby7JAK8c0B2qZWeUPEQ6eE5DSgKEiBdfA75W1xhWAKxvCSPYC7YH4Kf+Ao8ix+wr6R045YLjw9ajfzeaRTMyoiWdwbveYd1CozNxvvxno69WIBl/VskD72rvv0AIc/Y+ifebFGMXVfb2sIHMl6Zg7QpG2NGcL+6xeflinwrYv9ec15DFVVwDsRp9K+C6FvyA8TUh8w71dEz3VcbcS2GzrDAKBCkAKuycAlHQ9o1TIliDbkm3OeSdvQ/qb4LZxKf
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
