{{- if .Values.persistence.workspace.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "code-server.fullname" . }}-workspace
  namespace: {{ include "code-server.namespace" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.workspace.accessMode }}
  storageClassName: {{ .Values.persistence.workspace.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.workspace.size }}
{{- end }}

{{- if .Values.persistence.config.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "code-server.fullname" . }}-config
  namespace: {{ include "code-server.namespace" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
