---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ include "code-server.namespace" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  encryptedData:
    PASSWORD: AgAUiO5hN5PE7T2gVURMKzIY9KjIn/uQvMLJYLWIBKwylRtcnnltSsANC31WXXM7WImhNIlZxRt3A6YjD4G3iqFvFBoh4DaNCFc9ljTO2RGh4KwbkqFRmmgR8IM3LsRRs089iYbllag9rPV7WxEuWwXH+iydp/nD4rEe3pJQf6S/BtSJds2FL47uNWPnaIuR6p/TKesUoBaVcQmuUjRYsyY5IXJT3BLb3wrr7IXB8Z8ETluZPvpQAij+JF4fIveJJOUXXmV2NWlFSHYIPLs1gv2wDe+j6sHHII7Rc5UwT56xNQsamq4iOZ+nFGXugtZP68GmCF0P+f9gljXlKEP7btF7vz1ERY/bDcN7z5lju2fshMDihn4mLzIsdtKLYdwUi+BlUKV63LwUrD/KPHEQcJEBG5nMzCiAnCbhoEID6vxQECFPojU8QmRcvUZ5t1fjo/r5B3uzL5NBtzEhw/gJ25UrcIQd4btp0R8kFvHVI/1jIJgGEOyoC5XurHToDZQqkMpmv3ygYCvlyHKeFbexAJVmUra4jkfKapDhHjzvhaWr9t33ia183dyNZUta7tY1wSJiH8U7kAYBzlV5hH86n/yVru67mSyWenB+X+0ewc/qTjX8Fl0ZJKg8OttUTwsc/i0ZGb/EzvVN0v3tRy25IbP0ZhEhb+3w98QLQFWuIU0Cds/5/9L648CasAtgMfbNpnpPOUW0irJ0Rg==
  template:
    metadata:
      name: {{ .Values.auth.secretName }}
      namespace: {{ include "code-server.namespace" . }}
      labels:
        {{- include "code-server.labels" . | nindent 8 }}

{{- if .Values.claudeCode.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.claudeCode.apiKeySecret }}
  namespace: {{ include "code-server.namespace" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgCSmBl/Vpz7/0Qs7tORX25BWoEo55rAJJJolEHJGO98IhGzEtL0NJE9BmWaXFLm7L3K2J0tIZcMNRcqzbFrHNBQkrtYYU8+HPcqLssEjYhhibaCoI6yF6NmrnfrQu/rScc7Q+ZS9MjqR2GI3d+lA9yKqeEnq12JUvW+vj6NMVFLxv9Wciwtr943bwPK+BqS7QilwwA5JOO4Cf5qFHu7/Bp95kzr8okKL4yiBfO198mV3W1+rmVjI8ObQFIxZucidE+i/0SYoKyF2NCa/lepMqVqI4oE7hGKOMCtu+Lbnp+FQSlqg0Dag8GnP2V7a5cl/PK8WcDgp4ic/rbFwTEG8PhiJ/tIZNEetzaYaSBNFjRAKrZVPb3VUrb5qqQyBXPbbKnYVgF7haeQ6FIUSCeoa1tqv79fLNxsp2SPOEsrxxy+AgPbAGePDNLjp3hLK1f+EMarno5r4Hn5Mth07JG6vQRLqoncu59BYRAxEUV8Z+khDTI0059KYcJm6uWL5MB2jgL6SzPsdh4Mi1xJSxi1vXv/f/UBQjCpSO2hqtgS026WGZhq720ALNUUolOKdcazwj4ZjS9Z0mvf3pluhtA0pdGpiTTpgK/1I1VuHf4lE2tDilbhN2NFM1tFiIOF60YLWLTmO4Xa4RINuk2ZvDdikA4A3wo3E1PoFn5KiAoA4DwGVMb/N5dPsYQG/Q2g2jDMaz7laAMkj+qOce41p+6OKOnZLTVmwswAxwYp987MqT/sZV1s5dNnPOuo3slsU+scp0SgC6k9tYfKB4oKF7y+g6/0frdvGO0M7Fvx9nqsC4cK48v6sCtp+bUBwqSetndAL82RcHHu0EY49bsDRcg=
  template:
    metadata:
      name: {{ .Values.claudeCode.apiKeySecret }}
      namespace: {{ include "code-server.namespace" . }}
      labels:
        {{- include "code-server.labels" . | nindent 8 }}
{{- end }}
