---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: librarium-mcp-access-token
  namespace: app-librarium
spec:
  encryptedData:
    LIBRARIUM_ACCESS_TOKEN: AgAehkg6wgGcgK95ccf/+FxcjmDQy/2DFiiiFLTtHHiTss9BRBzFwzFYrjAq2dRKhg5hPvfmLYi/nvpdqb5yRADqYVNmf0pWRH2cMaFRy+bFeRW6Y1aTgAVTyr3b6dJNe7U/sbxL+YPPdbWv4nM1ksmcyQ9kqvG7FZPvi88rib4HX4WHUqqQ005K5e4C+tIjKcv5npl3TRqJ3IT5VCFvxwI6/G+GWl+IefOoDWG/UOMUD+8uf72PC43Wh90gj3oK/jG/sAtZ1wd3iQsKO8+gJeKnQkurcu47xWelel+h76dhHRIYH7X3jIHd8vO296rgVnSAao1PocPmc8uWlJ/33Ey95nfoV1cE2SSu5dHveKBmDNaJ0AnPQyqkdqLE+SU1Y7VGWHUU66w5d1NTntEQAWujti9JsWIyGQwrilYS+2t+9qNOidHKSSg6EmEvKBnk8K5OxmrBG1CN3D+21M6qZ45Gz50TgM8deHt6VPQ3WmfpPWcXLjEJyHDr6ILynpA1JdQi18EURyE2xFki4ANJWY9DZrehaYfSyV1X0bmU//TU+9ic6FNrD0oRBmSjQ2KusQFC/YTpT2Z/OpWXYmCDVNpZ0lDKY3VdHlecIos5rF6+B7ueEyfJIW8jFphdON8AqHFGUdtGtODml1ALjtOwiTs+w4ZrFQI9zzBLGYjBF+UQqPkanyKLg1FTBRf3BRSa6jgEKIJQfaktE67B/9r+52w+BUlgiWAfwBOnC0uT59z3Yb6ulDuSAGOpxbhIWkUUR4qcnQXj
  template:
    metadata:
      name: librarium-mcp-access-token
      namespace: app-librarium
