---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: librarium-mcp-access-token
  namespace: app-librarium
spec:
  encryptedData:
    LIBRARIUM_ACCESS_TOKEN: AgBJ54atHPRVC5knqAlHAFYJbCcao26vckWB3T5fyzubaRnnEaZyiYonsG7A7YdT9wS7fbqnGb1vbPt95m9uQF56S7SRXbMgf+lWi/6E8vph4PCuM5EhSzLy0vc5DVkUT/WaWVQOKzfESTNB0NowMwRzGQpnIcbrIR40aVV8lejYawefT6YD30ae8nTF4tMwvdbH9hjSbB4iIpvQgxxk7Q7afJzENE3/fK3skAqcig+ZM3EGtXLqXP7CBYo9u0xZFqrJoJycXdAfEl5Vj2T586UyCvn1Ux9xyIdfiHJOLd4dvYHQP+ND7BJbKOw7uTUk8gx2X9AlhFBoUl/razyw+gFpAS8y6NcWJNbhTgjBafJLoyl/i7J39ijSPtB4Keq304dDqUC+Q9VQbMCucYrbu6l/oY8g5S2FjD+BgImc1qkPYA2PUeBLxvd58k3kUIVjHNiG+rCKdnoFn2B3vrnFlNlXAKUeIfGLn3K+dzkOYLjW+d3cIWrdbLAEKU7xMbhRUTZ1kqh5Lj46cgmV9zPAnLDlSwB+0dGogDkfPCiSotaumzgNLfWvsR/L95qqhmGvmEuI3Z1TIWY43FU3RAD/CE7077BwnWSurxXWWo7UQw8OJmGO+thEOazISu/yuEPFVPUpgm8xa9JSF8pkn3+ToZzQBFY1KrZExWcF0J0A4SFZhP6LLYUDIs01VcgAzAzUmf4h3ikKSsXW9qgrT+TzHQ+9FWyXhnfSp8ZW5XBOGAVw1WmU9IV1drK13iy+w9PnrqTaqYoY
  template:
    metadata:
      name: librarium-mcp-access-token
      namespace: app-librarium
