---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firebin-mcp-token
  namespace: app-firebin
spec:
  encryptedData:
    FIREBIN_MCP_TOKEN: AgCa1z9nYEwyMh5RFfUTTEeyTWtb0dWMYuInJaya1FyFf5U87tUfOjddoxilgfjn2nBUtHuOxxn9nn6thqfypRkU0iMKqmcgW9iHh9eNQwOClxAvw5/Cha7rVWg5vMafMZODmBP39znz0LLHMKltWa96OFoR01PbjtTcpIYGZFrjIUGNfZbzQM82OFops46PPKLbr79fmuW2kg+65kWypdf6OPiHDFTSJ/BiJECXFgeuMU0z39OGiR8X4WkmeJ6X1LcPvYQNbeIsR2EbWXsAN8FOZ30aId0cHm2+AWUXpyHAud+6IBKhg6kzzdcltf+87nd1369YfXc3wvOBfC9Lg/YnVe8APq2P6GrzKVLuVVvSOXwOR4miydYrf56FtRdc25SNMFUYyxXmsjgRj1uE3qTpFRzBJB+g+ZErQrvH9BXfhhTK3eOTCSaY8DCIgGVR6uDSU9IQlZuo0tLKEV5TcAuEpWjjzv8cZJAc1FkFBNqDzAv2bjg9jwl4t0EmPIFx0tdedj/7PMP7RlnK4n35CREUi/M+a+gyjBQr1KKWQiM0MzneHU+/v03KILdT2637oDct0Y5IDA+pUGqIsjkNEPwtI0jLTpx9OsbKjpOUz5EnXe7YGypgG7VwCq8bkGXNg01luZfZ7nwPMUPybHNKiWrJb44+8U3XiFYmsfNI/0MdUgjOPOq1x7gWw0WW7aw9Zxz+/KieN1mB+yutSAt3tszDc4jw/TkL7w3Xo9tt/iXEe3dsLvBbUH363p/oVQFOZeZeDfrX
  template:
    metadata:
      name: firebin-mcp-token
      namespace: app-firebin
