---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: app-n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgCu4eYhlJSIndVabs+B/ggitNsbwSz9VLVgNQ/U/zFWUg4QukWUYiEdPe7Rseh8jN4dIi+5NGY0e+OMpOMnqK2Jz29VQ88J4IZ1hAbIPNIk1ARRwbMJ1nrbzrYCFlNCNPGYhTlGj6kV5gAbumS2mR4xgjA3MR0JHtyP27E0H/mF2BkV/w13Rrb3CNGEH6cd1OpAoUnvVsSf0/k1Bm1rlX2inGM0XXkYJRVZIU7XOdIZGaW9pUFU0c4RKJhXCDVxieFBpUBMp3sgjWaQ4XRfHEyhFecsEXXmKr1tsE3ClqBvKVLNyYLeDkQnn+nBSANsvh+r8Cq0BXuLrWh/UuqKDrcZ38CdQFulQW3MbBc2EW4KK2AKdYZj42ut/M+wOnWEr72EmTu5bLPttF8nc8+tH3yoGRsXkXAigxEtqJnX+3EW20LUKD/IOoZ6E1ILrLaYW3MjtHgLRCBy2xDgPgHsy+9WPklbCG8sGGkWU0cjGGel9ES6C9HltR2757aE7tG836n2i9jQFeqYKyFfrUjVSb+4Oj3YqpDHYctZitQE1+mzpA+MW0QRDAMzL6DtR4ifZgXxRSB55qJl0vtKFZuGWt1cS+yBMl/h2PzLC5+l4HRQ8YNy5v19+mEcTfV/rrVvJTBw3C7VIrmPzjNFqVCSfzqthIQOxqoRzxbQI+QKkK9/0/H+CvaPqJiNa8rj+OvPFJqIo8yFmXAEWtVpiw0h9tMI3npZxbnoOjseMVRlFWXfjbcQ7RvNcUKf+5o+25TTS/g=
  template:
    metadata:
      name: n8n-encryption-key
      namespace: app-n8n
