apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: app-tailscale
spec:
  encryptedData:
    # Using pre-generated auth key instead of OAuth
    # Empty client_id tells operator to use client_secret as auth key
    client_id: ""
    client_secret: AgANUT0e9/wyh6Wy3GE8h8l0AkabczfcgDqgEnaQtUMakKzM4Mkzq15UKSeoEeI34ujkvglKBiXNImK8sK1BvBExPeP1Tyedaz1iLHrPC76Hd/LSfzC5Fdmu3NYu33RRYb99iRg3i9Pjliq3LLlH+iLZuolCi4feX7zcRvA10rjJb10kpC+cSrVF/3rQ0md75gYblo4JfcL7h6k3TTOBix4l5yUlgX6zVEZcAyOjsNsqD3DEh4Kme4g+a5c0HYbM0k2vvoh1s7iUGn4nEVVs2fkQiZsykM6CjIkvpCybxeFA83fvlksg6KEU3p2yPdl1yqaRSHGRNj3ytFqwvRbbBcRjwPV8XNSshiFV7wW9VMEXFE0u95MclR4tLY0oiqpY+T0ullteO7lYZBm7YSK+1TuQp6W6xcfyaFBCJaa3WJKe72ZALTZwE9pCbR2Hfw4DtEFwZDPa2/gtQJkDGNhvJhK/2UkcVsM0iegHTRpQ4YRw2gqyCSeCl0gR14nQMib2Un5pk1sgM7kM6d3+OHa+M/+E3rkWGReSDdyTMAplwwyjIQZi4zKx1r0i3vWh65fX7M22Kvhf6kXrwowOfs2Q55KPBdATDLu73qCxZsLeugAfc/R6lJoGeabROKCmRmCb3mkiXW1mVgO82Z1IVTqTcvvbd7kRRuyN6bn01dSi1GNiyO45/Q/VymUG+WWHPaK3uI7hMYu2E8DQxjhXzZ9uQ4nU6Yb+tKd11EOlRL9Soy+Ndo6+EyQIlH+11Q9SMW0qvET038fURrZHweIcyXQCvg==
  template:
    metadata:
      name: operator-oauth
      namespace: app-tailscale
      labels:
        app: tailscale-operator
    type: Opaque
