apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: app-tailscale
spec:
  encryptedData:
    # Keys use underscores (client_id, client_secret) as required by Tailscale operator
    client_id: AgB4tw+9izfLtXmO+DW+eRy+Be7Hkuoq3wtSBMBeEPIf2XrGizNnpTDpBATl9O9EsGmBOnhEDp0bJxO8SbFp+W1oxV9a23ZWmNDFLtBkwfQAZbbVcQ+EmIhN4lnnXObwaaaocjCoPRR/utGjKVmcKkS+eho+E2R4h0SaSrAIHLx8hoA4Oom7QB7rT6bwUSYnwgsvWhk8cEagoiifAbrR9uFnxq1pp3nVk3doa/Cl9U9G8/WlIqKLWGMpgPVSa2FRMEqjrFg/fGm82CijcH3stewT+R7AE7EMMHw27tAqqV12oZfd1hqsIFlfUNIkd1MD4BP0b8EukYiLZf22ycUcJUOgZ3/vS1mRDN7ocZUVYroUUDpJGdkzIv9rPctGnPlQerSdDOTtUoKlii/eFnduAm6aC2qsWcY9BZ18d6m5i/Of8biNzw706+D3ajTpQE5ASW9pdxorzUa/aV8PfrV7ChEg+FumZ8mN5m8QaxRiAHr7QjgWqOdP49k9S2CuGSCTE+hroIh/urXBSs6GFC94K1Hg8OxCjI0dxIUingV+Y8vKLJfJIOKL5y7F7iEyknxqC6Kk+ui5qAc+g9Gc0Ks6fgzwKBAKmcDKVdTOraYiUfTHaTKe50lKcnT3VwWuy7lhIgZS1p5djcJ2/E9ruVchM2xX8NQC5TbWbhZu9c7iY2vVyq/Ma85/WVMTgMfAla/tfZNS5xkrwVZddu2ScrF2lnc/AQ==
    client_secret: AgAZreCgG3ykJ+5iV4RbuJ0L8G8zR56kuaGMgjZtvHe4/IrEWW1SBJ9Zn7FSK+XJ6LSt86XwMX94Xifc03gLnAWk6LH3+CotVGXrQBJcUsnH3+NCrL+0XCh86zJ8IMZGDR/NjS2MQNBOMZ5c9DGZF66TgXeIeLfPVYmpIMixX2j9fkpIs3zN4WGeBdDSBha7hc2dxtuZIkZb7m7IQdhCaQvyErX27jbzhSvFcd/uC5MiKkO7WS9ssVdBwTK2BC5HCGS14KAKESWeB6LH1vaneQn33RkgZ8wwjFez8TrmdsEJj0TE4VEC/yPIUWKnahqRXyO/1M1k6U7tpVuW4HwBXPzEO3ciCpslff+D8VzPAr7yDrl4pmblWgWe/+djuvmlx6+7vZ0c6ORnXFs4BPUhFLGVmXAjuzMj20x8+jUei0/JiNLTrDHtlxR5nTvZvzJO2oVgw1qPnGn7RYitXsQvvty/YGoLNm2HJsU0MzcEj9SYhf4N8LO/bBHrHNf2EFzermbGufTtufsqtMuvhTKV6K5c3NDMFrSYZYhmeplEbvdZ51fNKvp2TASQjzKfcU2vjdU9xLAiGtQ6zDmnzEMETpM3anq36cyZL1/pDvvo1GW+E4kS4CHTYohmFMssagdvb1JBQFDg0czra9UUl7AUSSfbO6o15+njzOly7vlFs9Ox9dNB+Cvtt3HS1VbBoViaHkpKKDl0/Ah/s8UGXkPS94e28wO44lqL+Xrzd6OnXbKOKscl9MAXuQNfGyKgD6CiK0yBunFnzLWxW30SK5PVOho=
  template:
    metadata:
      name: operator-oauth
      namespace: app-tailscale
      labels:
        app: tailscale-operator
    type: Opaque
