---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: upstream-github
  namespace: app-upstream
spec:
  encryptedData:
    GITHUB_TOKEN: AgB8BsqFBbXBlJCICfdl+98lJvRksjlZ8Z0AjyXtI7abzQy8qN4rHdQ7ZmverfCuU97Y2c/b7gFqvAyu1RcYm3gRE4AOQOR60ptCFvNHHFj/dEpCUI9zpN/k5VwpD1b/zayB9UDYfChCvEm/KIm/lqg8ZgkSw27gcj98FbbJHATURBVWih53stchEh2SY9OfXBlI69Usdytk0rHHPMvv+QV5K9wmf3sqUD7yZiA7w1MkL8f86nE6vIXHPj/YqtnhxJ6Arh0McFGhJHEV64ZQwTHc/1+emY9fs/wz/UpUdHLgzZKZTDh1eyl9bE42fAY3MQ7B0d7S3ArkMpayqpMDzOyBGHkDg5Mojvw7XF1Y4ShUF7NnBUsRcmH+lv6TnKvjuES+RP0bIqLO4FC6abd+2mbjg+LWfj1SYEgXL+OkZFMvX3N4OyIWdqaLAwoLgeJ91EJyRUfShFTKF9c7afq9jh5O/2JiubbQ49DAe5RRoXwyg9Ra/KGSxdSO04V1DfBWZO3sGtCUUKlLZeKxlEbixHzjBw5lhFImIH8uyYX0VqTFGowD7Q0QJd4ACEkzeXfuMusVqLQ8moJj+kEiJRS02mM4YhxAGq7IPPaFuRvcbiYyEdAZO1O0UCc2sF6+6zGhJtJz4KXrQebjnHbzlgG2ZZPnwzhZJtSTAe9dnk/aPRiaNVGv3A+H6A499zEkxZ0qCpm/9mhdBd9P1b+No/5n/CVF69wQv0n7zEGlDBxz9OTyQLwk7otJQpUEzQbx3y2dRam6W0an6fAhaKyIsmi9Bl4BbjDcUVMZ9gLFYtMUg3TzzhlMp50teLFs1xBnfGU=
  template:
    metadata:
      name: upstream-github
      namespace: app-upstream
