---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: librarium-api-jwt
  namespace: app-librarium
spec:
  encryptedData:
    JWT_SECRET: AgA4cHft1CnyNqtTifj513syLV1G1mx3mWGGYBw/TVNqR2krV379trINkUFct5ApMU+4W6JVp4b69QZ4n2S+Ce1qeHYP0GMbHVsVnsQnViYFcBBk7RkpZtzl8Fh4SyWi4vCjjAJYTLbfR7zhBT3CvGRHYygNhctvw6MYCdsbFbSCJIEKQv5SISCd5KuKdMMIZQQEuxhyePBu7Td9u9FFZnSFaJqSV43NK7ByMPc8S2aFk18D4LKANdohCaYo6ABzgWQna4NgAi6NLfNXndMatxO4blTfW7eYg9R5RoyqZjX5Y6fcs4MQd2AgQJPBUX/qbBt8+JRCBJUcUiAXNTYe4tiQqPO0iAG2ZKigF3sxOWAUdAaItFbtr8mDSRhOmYnzl5bbuZnjw5PAnzrTEULD6+T0bsRC6wOUUDHou1XR1EQ8wAMWAZtTjiNMe0ejC566lAyIlSmEvUhlwMCGlCtX3QIQbwpAvw8nyBONfDydUItxjMqGq8jq4tZ9afhPDGb0x0DR20GpJY2lALA13TXcKQNZk25jZKe04w1fA9z7bni9kNn6ofcmMnInKUV+Fs35cWtEtRnQYaWunTVTQJmxQH9WLS4mHdCh/Y2pooxsSgKeuoUBF/ZFKliMjuFUoJ3qu/nDWMvWgsimt5Q/t/zz/kEU7mr3gWghicmXh/1AC+8R59tGzOBS1RQxAWc7ZJSB0yE9K4Vw/xAmvzBrHIqO1ct3c4uvPaILtSvAdZ2abHLqoHq/slqzCjXfgByj4QL2Q3+OAUPmdcf8pLNUAcoq1DY4
  template:
    metadata:
      name: librarium-api-jwt
      namespace: app-librarium
