---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ include "ttyd.namespace" . }}
  labels:
    {{- include "ttyd.labels" . | nindent 4 }}
spec:
  encryptedData:
    PASSWORD: AgAzv5xfXR9669Lqmqgg1mwIxcYq7ZtaKJZWxkhFTDUhiFK0mCI1bOr02zZV2rKMsWA4QwYVkushxP4r2uUkuP7bDatAvQV+HOjVnI9aMmjd0FCz858m4mCx8g6+lThUXrxMwmGk0dCDmuKqzqkfYh7loKk7hHVjbLmpvclpLNByWr0UPN7fdyntoDFTPavEQ5UI4d8ssvRIfbYC1LaHZ2W9gDkgFgbppwTN/4DO5kBkL6GOy5aB5t/3sinCUJKtxzWmEmryw7GRTOPIKYMVu8EdmOjhDBnriE4pwMTWBsMj2M6bMBvMr6jewYwdNNsDjX81CxcNCph+os+Wkm9YYtpA+pKcCJr1EPd6HsTBQWc+TjhWOZD2mGjqEBM5qXqk5L+uhuFPrOC8sjpMgfSXCuZhEzAAJJNEz654s4Ymz4kPYOQFtfjYxB4vStmA4FNc0x54ViT4akAkjXdBA0gQlugSuRW0pvLuVz8XW6BULcnt5aL+AayJdatosL6nPRbrPonThX+DBUlGeFodK/qTnL1Bv3V6OIsceJnKA9DNduL5YlbL2Cfq30hnYfMaw6wP12Si5NKxR2vS7OtyaQB9YwQa/fqB+xWwi/h66yigCJxFgye67c4slNyZEBBrWgfWEfDMEZZzxBlCvFMoQEWL+QSa9FZZlhdpRTj/nNFTSTaoblk2LG1HXgI38xLe5bkz1T+k+pDJjWcMNw==
  template:
    metadata:
      name: {{ .Values.auth.secretName }}
      namespace: {{ include "ttyd.namespace" . }}
      labels:
        {{- include "ttyd.labels" . | nindent 8 }}

{{- if .Values.claudeCode.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.claudeCode.apiKeySecret }}
  namespace: {{ include "ttyd.namespace" . }}
  labels:
    {{- include "ttyd.labels" . | nindent 4 }}
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgAFHxoSFus87V0CnHIKv8bMoKgHYJNV4spk2NJkWsSaT/b9CpcbXKd2vAcjm6mEiVqN4RaSAqy395LnRG0PtOMhgq9fAvpxMmKgj9J3qn2RIDDL7dqWnRQtvJYsf08QxLdLV0rRpeQOEy+rkbsDy4LtzE7ABZsJrvhqe8GU+oKR5b+k1pZZdnJpAKJZbtW+w1pePI2lKTC2/N+2Q3JXjQIZVfrBw+wsUVRUGa+Ql4WwgxIzSKjCDdM01NEjzdn29ekEhOZe0ZWf2C6295a1BS4gFxTQ99GNzGV4mBi2u0cCjA3PH7q6XKu0b5Vgl861DBC046q5JFkE0Nda1ZOAb+EaywDEl5yfbIoxe3vgUZ0cxQpOuBRtOWmkn/md1SB0fuysyY61BasqdUvcmyuXOUIFBoRwoUITYjm3qZZpdN6cfiBEjx+Ubrp6T8GAJ8rGESZSOeJel+QMSYZOsTVhDoSH87A22NPDPKFAZw7I8agGwvmj8Y4GCUHliZUq0qzpa6F2prEZDIxjaYwy1WTvrzuEBKNYVH2HRqp7OiStHqT7Z44WSVjanA6XyLSeiatBRRrK2F/xlOGNNN1FIt3ZxHohCxRoKOmKRb78jeMvuBwvh+MBVBSByobgQDioi0Q7snIlWWH0fmSCql9xt2Y2NAuowbovJUrG2noVvUlcTWWw+ZodZIGxlvBFUpgFiapo8zSRowu9xMlQnNPrm3twrm/eku9Uq8UuTr0EOBLivNfyx1FgYT/9A0CzxUJ2vde/ScNq9j9yjjy0TfL4wJxGcCevgleQ6unMjR6nF/eWkYzCosDrE6I8ZDKljJvq7O7T/vmhacpewPqtAYRp4fU=
  template:
    metadata:
      name: {{ .Values.claudeCode.apiKeySecret }}
      namespace: {{ include "ttyd.namespace" . }}
      labels:
        {{- include "ttyd.labels" . | nindent 8 }}
{{- end }}
