apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: app-renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgAbQbq056CiX5TzJOB7SuwFVIUDLAbT872Btm3Gm6XP0i9n4yk4hib7m8EP7S60my/zz9SHfzotrF0qXTJwvQy5mK9jLps7DV2S5+py4OYU9pE8HiEx8k5o14//t2dOpgFyN/6DaXk5vws8BW/Xh56GRJVZIrJxSnd+JvhcQgxqSmo0lVYuf4KmzM1eqruZxCkiWN5+sDLh8/9KKlUY7t2RexgFsPdLD7ynxdxyt6+HNmdflTRuAEOjhPHYR1jLVvi5Q663poYLOeR8ARTrqIyiwKkoNdj6V1qIu+wQhtDCLyyHNi+57Ybm2k0UyuxJH5q5DutOmFd8SjaO/s2jnxk3sFeZzgeui9Y0PET4GKH1Zdm3oKp1DOLZS7AZm2WQ1Wvq+9ptKweizWpv0ZipmS+IfSby293Jct8cOQJHqi0Exd/We0wCaQ1r0dC15C09F7tOl8QqrgCU4o/TCqi7rkoBtyuF1PTQ+DUx21DOTfJst9QNqdjCELk/kR63WaYvL0UwGuX+rXqpbD62fTVAHxKTHZR1IjF804YNZ/4TETFddbEYk5wE4hU5rKsao5cUWC7C9EJEC9HPe4EYPDpndukw08qIqPOb8IPCksXMNrPa1+Xm0yKfRHwf//Tu3/X9p/K2/tEe2KbsmxxASxXVCNXOTh3wvZrWs3bS3hx71czOSbnW/xqzCjeAdxUvwrh7hsKuFzBUkMpSJS1VlOBgNdH1yzzjMuzENKFV9KPOKhG4yOuovYyn9Qwb/+AtpvFXLiGJRb9/2nAZbvnd/swW7Lwngi6oWnT26VgG5J7AMldh7aZmI6AtJep9alXzJ80=
  template:
    metadata:
      name: renovate-secrets
      namespace: app-renovate
