apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: app-renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBimufBAjsx6XmqCVbnwts8Fy3K8xFYjB15IEAFFmWwOC6Po/o0AY9A4EAfC+nBHpHv4c/8kKg1gKntmLgfI2q6SUfZYM+VRWb2PlJPNhXPT8Qldxtrb3TNwP+w9FKUvhtvIOjan22ywnPvQLLw6odLDujtVa2aEyBEgh6UELJdQEZ5xTBvCAKY8e8GDVRyVbHwwG6yFDj1AaI93s+XZdxTmscOGMG8/KJ8IHuVPgfvggjGckDPaxeu5LCAYm2xo5rJ1OU4tYB8Z74ixYYInQbQOv+MrRViT82f1iJ9AMQdwtrdTfYkjUOdnXQ6EcB7AJbumhTbjSaId8Kct5CjpazsIln+yNvDkbtNfUTVqNveP7lIVmv3eTdPRoMNftZnfkc1GYn66fO3sJqub1fVp13m32563F0Mry3ulYG29bnhgLs/UX5s5jK9zLQzzXduQWVID7rXjg7lz0uPm8lwGCTweFlJR09yt3rw4jTJi90CNYBh/0wMTH0LgoY/7kwnwLAh5h2ea/a7vt7PTWilxRrnB0qMlSSeCBQwadhRyc98Zd0WCj+TqoJHXccywNKCTyg1Lzm8Yeiciddyj+iZZuT9VTc4VEMYfUs3YnBPH77dThYbAppaE7/drbnacZv1YexjEuK/dug2HlGpycvs1vgr+5Na7mwWEg1xkPGG8Yfb5w8bnO4OqOTjvcy//09aOUOVVDMDKDPBi4d+bmPTwoR8NwUuM5u/yeUtG4d4sP+tECibIS/7tdp1SaO10Opp8dYDY4EjPTFOkZsTExzPmbm6NKy/0qJkjIyXFwpCpc2vIsNZPV5+3O5U6cEHlO0=
  template:
    metadata:
      name: renovate-secrets
      namespace: app-renovate
