apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: librarium-mcp-access-token
  namespace: app-librarium
spec:
  encryptedData:
    LIBRARIUM_ACCESS_TOKEN: AgCAV+5X2AW8XdIpH3SQfQ2R/ZYu0C7AyiDzoNS9I40rFqWmsUxFtG/pcI48+jNePTLhPRZGRxr5XOcmbVrv7osERdbDGuVfmq18Af8Z6v+NP4H5eANVUDgCjxjWEDOrqqagGYgJ4x/3M7fljveH1mec+Nl8i2QqT4McqbSYoDO3aMR2pJqcymQTf6lOwVBGZ/gx4lVN92Dq3F5/0fw0K9k7Swmq/B7KHplplP5aOt/P9Fbgwx1b1OMFDiRG6otpu6O9d1FcfLTAcuqtXzEY1ywIP6DLzw06jyqFW1epVqNg9/Eai/gIh+2f+pTXWS4eJsLYvDjPW8hvtoZD3IpJmIgcIWXUPLVeXNd104u3dJFQTaKZo/bVUP4Z4YFJ5rv9Peh4sGjw6a0HptcPISEviKosc5gQ5GAJ6nlC3mBpXzDAABDo6GQ6lFogertsRgsR7WvNkPstDi2QyJkCmXa0P2ZjfhIMVKckMo+2He1VuEfYm9KLDR8JZ2FZCge8UaW3mwfFyRQw3Ts9+PNyMIQfs4J5T8XRx1wbmiGY8UVzKjTQsRsqL3N+8Yg6ODpA+ssHRLFogk1lP8k1DR3WyJPDwsMaUgEpzw2/Wh61iuV0hLD+u2AfsYCb99hKytvcsgs2CfFZp3beKakHZDp8XMTldwUZEDkXdi2rc450X1Ym/SSQD6R/VzJvfuyvKjr6l6wsgIEROBqKuyjzh3szyzyKTpqhSlNJ4tsP9dNDy+IY72whLsRoZ4gCBB/Pta2KerbeplWs786k
  template:
    metadata:
      name: librarium-mcp-access-token
      namespace: app-librarium
