---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-ddns-token
  namespace: app-cloudflare-ddns
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgCRjHp2gnF4WGmIPbgJzLMmwz2gOd6vy4XhEZ3m/UQzJQP58KDk7MSFUAHNdissiwn5m0JP5t6RfUtyafsCyrJ7WW6YVLIHPykA/H8wnFPG6bk7e5kaeLr+1QAiOuEUHTRyz5vUJPVRqbyTVliswYawReUrwWTDLaJyF069yvFUfw2lLlCYB1IRTWAF0genyHXcN+1lj1bP6TRHQ7WoSoewSlEFbjdW+sID28WRTI+okP8BE3Y03tCzpFCWpL95NY3rSHCqxpDtHB5VNY8hb28i8l44pjXvbS3ktZWArmHrKXxC1CWaCzbvG4FO54O9CSUsL/Zqku/WBgh+GAKH6H3g3d2B62dsJiak4EQ23Fl17m5LQ9yIVLK8RKwH3QFGb9Fput7yJn5XwlmovvgCiu1mTv+nlruXT33xZ+eOvVtCkVx46oPhXb3Nae4Nvr7VcC6Qsqq60JjyNAaZbg5lvOp3YEf8TuZDOpvhqwL25fveuWCjWwq586K8em0/QTCGM+1VhW4j2kjm9vyCPJv00f1vZ9w4CyoHS0PXm/xJDlgMNdIAmMGzkdqpwRXd04ZhyR4zcNZi5E4eCnSyPWKWUnzMhBN6aYnnVdSpjSm84odr4C8x0StUtbjykUDZNzF2o6TU0w+99PrcL/KUY8ouMzDjcPc7Hcr74rW8hHrrJoKVCGavrThdzFxdeumdDcgfr2RTFAwh99kuTuLSOYTlT14LhDq7+aGTxGrIfktobkNOEPWq8HeQtEqZ
  template:
    metadata:
      name: cloudflare-ddns-token
      namespace: app-cloudflare-ddns
