---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firebin-api-jwt
  namespace: app-firebin
spec:
  encryptedData:
    JWT_SECRET: AgAUbPiOldmwpafQt2jmrRfT5KEyGXdM9WSxzjmrwk9sxEPk2+xGJsd+qQsC1ahnAcR1clqhbvlWoJuDKRXitfS0bxQ/7Xb1wJ2yHRaspdJLn67mECmrY5aPO0soyA7suq5d91ykd2ykSW/EETgW+o8Fv8O2qKfu17aMPjzusyzTw/LO5J6BIIDJMo+Ihz52nVCuowBhCxM65qylNERIxRpqtAOA5uC2eV2BTUbtv6udtOecbJivjAbXlRfBz9u7sUYGx87JUbBxciXlzxO5p35imMaggtrXt1q/zOqidRkJd3TUYaj+xSSabikP72fviexAVmzPmOOY8/OGvWXgQRZ3Jkkt2lSqLLWEeynYpEzRmKYNuZtakKgQqcHkdK0Okw0d0CmL8oapEnooF4Q/H9k3E3ZM+up0Wxh6+SEninxbiXpFRsnPeWcG95bHdxO72ktCb6oFQiqbogmnkxmR9WWo7p/5TQjVW9Xgwr7MkRhjfbUeMhuKRmBJtrLtJqwv6Y1qV4BEyoODH3qjJXkBu4a0w0cLE22mjjgAhhCRMxOvJbCc8o/DcVDoIvEH8+/LAiW20319rijq9uGAbvlmwO3Ty7O1aAbgkcxJG5aOPNvC5zc0oToiRHgDdxDM2t7pGUDh/PmQunXAOeCep2zyrJh38r1cOpj5CKBvC7nHzHfIG4Vakc5J70jiI3R5rxXBNUXz7MG++BtZ7g+52bjxDLW7D78ZF575XCNVbkP+ApziDk4qGmem8I00Xp8h1UQKK4GGObRuJJyGbDfgQ+2W/0hN
  template:
    metadata:
      name: firebin-api-jwt
      namespace: app-firebin
