apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unpoller
  namespace: app-unpoller
  labels:
    app: unpoller
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: unpoller
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
