---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bambuddy-db-creds
  namespace: app-bambuddy
spec:
  encryptedData:
    password: AgCuvc9No8cVg46B1vXvChGaAvfrgm3f8voTO/m+y4cnxVUXQuQaeqC7+lTArn1SXUjyEchl8muCwpnDb0bu+FDxdS8n0liBz/G95ktt/1dvuCKRregvrVFnwgTmtcSGNSEymTvmz6x1CPgLX45sBgeheW9itoMIFv207gc5yaZLxLxfcZNx+EX9wKN5clvcSsj79YAlimsWeeyjTEQdtzZYLhgXPEALEmJpViLJfeV0G5jzNxmXlxlex+iw3bDAsVRznVfdfI5tO1QgibGxJyASoh2/y3EJOnj/Vwn/bSrH2fiDf876p65Jd1Ud1YQu37UN2wihs/SbsttfQhMdS+1UgZsFwru6/BTIp2zssjn+rQrwlBwppU2j0XRX42jNnTyR1NDIu47bB6uHJCjRurxHUV6CG6k247oZzTVx9XMnryZukNIeKPBe8EbXASqbHIGuG+4SKmSbK15XJwy4izbNH6W4XQ2Q/OtTR9PA2O+lLFB9Npumiz2yHNbq1YumNIhx6CfB5BXcuV5O5kE3nJ1OOlUqYmdU/TORoROrvGbo8NyyTE2uHOYRBSb5tXzESLTZaKG08Q63nN+i9gEKL14w60oFih+U+oemjCSiisR2/ImrNWY6tKnbS7800XARIuA5MfrGYwgXFslzVaso+vWdRZ1S2lAC/LBReTZImgTwpXjStK5IdvJJTmppk1dfoHf8QNGyOvz/a++1K7vVYW5iAelAZalOFOXJPU/5Q6kBwA==
    username: AgClDTij/BybbrtPxnwY3Cn2Y9xfSaJIeEJFp0MwOU5VkEVYSm5wkGBYXdk5EDoxSXn7oemr8F1LHx2WD83uDtaIVPCSqR2S6WlnRKLz3GQh4nt9Z2Otf60FC6uYMONhBCD8VUEmTkY/BwH+OpF1O4xCGZZPLkbWCKr6i6j1TCOG4rbIVSKWC5Gc0t/UofTirOlfnrRwkBXcMqm66IIyJpehuZzR6WPnn9/lnh8y+Mq5psd7iBAgAfqcbHpHWCc4mnrst25nSHks3HgQFBxT1TArvUnKMvZ58o/m7jKCDSTzkkc5Vq6Mjr3dCAapavTvi7YtGtY0BfEgm5js+LY5Aev2u95ZCzTYI0kHPMothnnIe1ZgZ1o/psOJfqtN1ODhoF08cB/JB7Dc00cb5RDwpEsaKdNxJxMy8yxHO/1/PvgSUJTLOah2Qx+17zKUzGR8fMn6+IB1Ddc6zE0TUojw6HYM+Z0T7Ey95NyHPrnw9/j8+rgwjBVXZ8FsB17J0HpOS1Qi6B7pFeplUe2NjifH5uyy6A9LproLwq3B0eR6xnefiBDzQZs0ED/lzyLnPkLB3ZioGqTpUQYm8Ee397BV9X9gTaSOELCds7u95oy6EPA4aobtBNWgh9Os5L0E4so7rfP+Zfwl+m4EKNgKebu/mioJe8NCmeGZZ5sYdYy6ur0D17u59v451EsK3Xog5HP+HRKhyGQbfmZDbg==
  template:
    metadata:
      name: bambuddy-db-creds
      namespace: app-bambuddy
    type: kubernetes.io/basic-auth
