---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firebin-kicad-token
  namespace: app-firebin
spec:
  encryptedData:
    FIREBIN_KICAD_TOKEN: AgAZhXxmenGQG2U5qu44IUEBo3PmbK8yrf7B3/AzSYPyJehNAinqytUj1VxvC7Log4jz++pOSp7l3222wj0S+s1ZZC2UGDOU23o0O2UgBrz9A06I8jdyI3+W0Mfi9J9gSdauqy3lL2uKpaXbrZpX14sCIgW5U6Mne/i1ojgv9GsJk133LP0qS5pWOx6e++82gNSlbrcQK+Pe5nLrdcmT+2o+DiLQ3qHG2l35iuIB6tOrcTemjZDdg53aWPZnCgucTvA91f0V5NdMxOOp+CDO50IUDzcH2mTnCnO00eaLIpfMCvvi5NshNPGX5q854gzS78dTbgxzzYXXwsYj8KS/+UhnNMkLGd+t3h3ORP07VIwWlgYhYT13R62wqcX3nWhxi46QE5bxmaV7j6xnNcd9KG/SQikDXltAOpjsLcanPalg4yQ2zrb5iBF4fjG9R0FmNasmuv7U2q6IuGLtOwQlZc0xe8+2ufQ711XynKyo5ygBiw4/9thqUl6ABrarOMkbEEHbLyFq64wLgERxd2QGF9EIQTJAnvtbRcG7PKMVwrE7PM1bBl7jWW7uNu2nqugVhhcEgnfaKwdWz0fWA2BOSL00UP7OWXwBWKlPcaj5RcHisgdvEooQANsC8BOFyULrblI4BcnloI1ioXtFyp3YtztrS0Gqubqw7o10h8T/lL6Coh/joj7kv3Lu/jBiKqWDU+D0EqRKOe+qfP3ToxZ71DYUbxbeWCQ+kLkAlvazMhNAQ7aEtp0lVn0wYf6XK/IzWsXntjupshY=
  template:
    metadata:
      name: firebin-kicad-token
      namespace: app-firebin
