apiVersion: v2
name: zigbee2mqtt
version: 2.4.0
# renovate: image=ghcr.io/koenkk/zigbee2mqtt
appVersion: "2.4.0"
dependencies:
  - name: common
    repository: https://fireball1725.github.io/firelabs-helm-common/
    version: 5.0.3
