---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: firebin-mcp-access-token
  namespace: app-firebin
spec:
  encryptedData:
    FIREBIN_ACCESS_TOKEN: AgA0pCLv/K/rbJJ72V/PIlA3YMYRVB0en1Vryp8sX97puQusYbzXYS8pO9+Dhgwl9iU+A5gX6qUaL+F9eyukmodyOKcjBR172q0ved8vqBfpoEJTqUkKmWpuJB8rURHSYmNl4YW6yrFyGIznjbaVosXV0Tt1p79VQubFV1Ukjb8IpWsBnBr8/bEVC9iWRuETHyg7Qllj41eAEBkfltKgFWV4GR40SDzJMTLYtyKo4G/OUOoHrve+Y6upZYAb3Ra/O0TX4cTzWlPm7H4EK457e/Z8hFw/dco3Ka3/zip7AVmoqD36xG9vrPo6ULc7hoCST0MxY007KwQf+BY1+pUIv0NrNvBnuHhKcQQCBcZVszDUxUDXf6Pno50KtYA2vmUaRvDkYOFKKQinpK+JJbfbsUE+wHvo/dgnA/3N8L99OOq43n/BXMQqm9eY5yXTJPBUkr6sruQ2JTLoE6Sfn1VekKwA91MwDm8ll6pcEC8XOnrud6i0ScI82deOkHEscYWOdvGj5j5Cqe9VDp64RBJ91iuvOoLj24yZUauBIY4umG64jxqIvLHhCyCW69NwrmSbyWYOLDC2vJarfMcLVjR+t7erGUKHrP7nMnGzplHiyYxkAfuyzkhS43f9bLgo2ZoTRG7Cxl6+FolaHEF34THny1r000IyWL7KFr0mtM5m96bcxhvZDkKsoBpkPUrp4pKVlBu6lhjmeeyOOeu5KLknQPjx3HBdscrVpc4R8yRGjLvbX60CoxdDiV9esBIITZXsLCMxGAHh
  template:
    metadata:
      name: firebin-mcp-access-token
      namespace: app-firebin
