apiVersion: v2
name: cert-manager
description: cert-manager for automated TLS certificate management with Let's Encrypt
type: application
version: 1.0.0
appVersion: "1.19.2"
dependencies:
  - name: cert-manager
    version: v1.19.2
    repository: https://charts.jetstack.io
