apiVersion: v2
name: sabnzbd
version: 4.5.5
# renovate: image=lscr.io/linuxserver/sabnzbd
appVersion: "4.5.5"
dependencies:
  - name: common
    repository: https://fireball1725.github.io/firelabs-helm-common/
    version: 5.0.3
